# Generated by Django 2.2.4 on 2019-08-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='RecipesDjango',
        ),
    ]
